// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}

type HelmReq struct {
	HelmAddr string `form:"helmaddr"`
}

type HelmResp struct {
	Helm string `json:"helm"`
}
